package net.kdt.pojavlaunch.quasar.transpile;

import android.content.Context;
import android.util.Log;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * ShaderCache manages the disk cache for transpiled shaders.
 *
 * Cache key = SHA-256(shaderpackHash + capabilityProfileKey + shaderStage + shaderSource)
 * Cache value = transpiled shader source code (GLSL or SPIR-V depending on backend)
 *
 * The cache avoids re-transpiling shaders on every launch. Transpilation happens
 * once at shaderpack load time and is cached to disk.
 */
public class ShaderCache {
    private static final String TAG = "Quasar-ShaderCache";
    private static final String CACHE_DIR = "quasar_shader_cache";

    private final File cacheDir;

    public ShaderCache(Context context) {
        this.cacheDir = new File(context.getFilesDir(), CACHE_DIR);
        if (!cacheDir.exists()) {
            cacheDir.mkdirs();
        }
        Log.i(TAG, "Shader cache directory: " + cacheDir.getAbsolutePath());
    }

    /**
     * Get the filesystem path where the cache is stored.
     */
    public String getCachePath() {
        return cacheDir.getAbsolutePath();
    }

    /**
     * Look up a cached shader by its key.
     *
     * @param key The cache key (generated by computeKey)
     * @return The cached shader source, or null if not in cache
     */
    public String get(String key) {
        File cacheFile = new File(cacheDir, key + ".glsl");
        if (!cacheFile.exists()) {
            return null;
        }
        try {
            byte[] data = new byte[(int) cacheFile.length()];
            try (FileInputStream fis = new FileInputStream(cacheFile)) {
                fis.read(data);
            }
            String result = new String(data, java.nio.charset.StandardCharsets.UTF_8);
            Log.d(TAG, "Cache hit: " + key);
            return result;
        } catch (IOException e) {
            Log.e(TAG, "Failed to read cache entry: " + key, e);
            return null;
        }
    }

    /**
     * Store a transpiled shader in the cache.
     *
     * @param key The cache key
     * @param shaderSource The transpiled shader source code
     */
    public void put(String key, String shaderSource) {
        File cacheFile = new File(cacheDir, key + ".glsl");
        try (FileOutputStream fos = new FileOutputStream(cacheFile)) {
            fos.write(shaderSource.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            Log.d(TAG, "Cached shader: " + key + " (" + shaderSource.length() + " chars)");
        } catch (IOException e) {
            Log.e(TAG, "Failed to write cache entry: " + key, e);
        }
    }

    /**
     * Check if a shader is in the cache.
     */
    public boolean contains(String key) {
        return new File(cacheDir, key + ".glsl").exists();
    }

    /**
     * Compute a cache key for a shader.
     *
     * @param shaderpackHash Hash of the shaderpack ZIP file
     * @param capabilityProfileKey Device capability profile key
     * @param shaderName Name/identifier of the shader
     * @param shaderSource The original GLSL source code
     * @return A hex string key unique to this combination
     */
    public String computeKey(String shaderpackHash, String capabilityProfileKey,
                              String shaderName, String shaderSource) {
        String combined = shaderpackHash + "|" + capabilityProfileKey + "|" + shaderName + "|" + shaderSource;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(combined.getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            Log.e(TAG, "SHA-256 not available", e);
            return Integer.toHexString(combined.hashCode());
        }
    }

    /**
     * Clear all cached shaders.
     */
    public void clear() {
        File[] files = cacheDir.listFiles();
        if (files != null) {
            for (File f : files) {
                f.delete();
            }
        }
        Log.i(TAG, "Shader cache cleared");
    }

    /**
     * Flush pending writes.
     */
    public void flush() {
        Log.d(TAG, "Shader cache flushed");
    }

    /**
     * Get the number of entries in the cache.
     */
    public int size() {
        File[] files = cacheDir.listFiles();
        return files != null ? files.length : 0;
    }
}
